DustJacket.pdf: DustJacket.tex Bhaktamala2.png logo2.png \
                ../ChanakyaSanskrit-Bold.ttf ../ChanakyaSanskrit-BoldItalic.ttf ../ChanakyaSanskrit-Italic.ttf ../ChanakyaSanskrit-Regular.ttf \
                ../CharisSILB.ttf ../CharisSILBI.ttf ../CharisSILI.ttf ../CharisSILR.ttf ../arialunicodems.ttf \
                Rupee_Foradian.ttf
	latexmk -pdfxe DustJacket.tex
	rm -f -v DustJacket.{aux,fdb_latexmk,fls,log,out,toc,xdv}
